# Generated by Django 3.2 on 2022-05-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.CharField(max_length=20)),
                ('part_number', models.CharField(max_length=50)),
                ('number_of_digital_inputs', models.IntegerField(default=0)),
                ('number_of_digital_outputs', models.IntegerField(default=0)),
            ],
        ),
    ]
